

pipeline {
    agent any

    stages {

        stage('Clone sources') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/master']],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [[$class: 'SubmoduleOption',
                                        disableSubmodules: false,
                                        parentCredentials: false,
                                        recursiveSubmodules: true,
                                        reference: '',
                                        trackingSubmodules: false]],
                          submoduleCfg: [],
                          userRemoteConfigs: [[url: 'https://github.com/jorgeacf/infrastructure-as-code-demo.git']]
                ])
            }
        }

        stage('Clone sources') {
            steps {
                sh 'echo "Cloning..."'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Test..."'
            }
        }
    }
}