

pipeline {
    agent any

    stages {

        stage('Execute') {
            steps {
                sh 'echo "Execute..."'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Test..."'
            }
        }
    }
}