#!/usr/bin/env groovy

pipeline {
    agent any

    stages {

        stage('Test in Docker') {
            steps {
                sh "$WORKSPACE/scripts/test_in_docker.sh"
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Test..."'
            }
        }
    }
}